<?php
/**
* ReadyScript (http://readyscript.ru)
*
* @copyright Copyright (c) ReadyScript lab. (http://readyscript.ru)
* @license http://readyscript.ru/licenseAgreement/
*/
namespace Designer\Controller\Admin;

use Designer\Model\AtomApis\ProductsListApi;
use RS\Controller\Admin\Front;

/**
 * Контроллер, позволяющий работать с компонентом список товаров
 */
class AtomProductsListCtrl extends Front
{
    /**
     * @var ProductsListApi $api
     */
    protected $api;
    /**
     * Инициализация контроллера
     *
     * @throws \RS\Exception
     */
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->api = new ProductsListApi();
    }

    /**
     *  Возвращает массив категорий для сайта
     *
     * @return \RS\Controller\Result\Standard
     * @throws \RS\Exception
     */
    function actionGetCategoryList()
    {
        $root = $this->request('root', TYPE_INTEGER, 0);
        $list = $this->api->getTreeForCategory($root);

        return $this->result->setSuccess(true)->addSection('list',  $list);
    }

    /**
     *  Возвращает массив категорий для сайта
     *
     * @return \RS\Controller\Result\Standard
     * @throws \RS\Exception
     */
    function actionGetProductsList()
    {
        $root         = $this->request('root', TYPE_INTEGER, 0);
        $page         = $this->request('page', TYPE_INTEGER, 1);
        $page_size    = $this->request('pageSize', TYPE_INTEGER, 20);
        $photo_params = $this->request('photo', TYPE_ARRAY, []);
        $dir = new \Catalog\Model\Orm\Dir($root);
        if ($root >0 && !$dir['id']){
            return $this->result->setSuccess(false)->addEMessage(t('Категория не найдена'));
        }
        $list = $this->api->getProducts($root, $page, $page_size, $photo_params);

        return $this->result->setSuccess(true)->addSection('list',  $list);
    }
}