<?php
/**
* ReadyScript (http://readyscript.ru)
*
* @copyright Copyright (c) ReadyScript lab. (http://readyscript.ru)
* @license http://readyscript.ru/licenseAgreement/
*/
namespace Designer\Controller\Admin;

use Designer\Model\AtomApis\MenuApi;
use RS\Controller\Admin\Front;

/**
 * Контроллер, позволяющий работать с компонентом меню
 */
class AtomMenuCtrl extends Front
{
    /**
     * @var MenuApi $api
     */
    protected $api;
    /**
     * Инициализация контроллера
     *
     * @throws \RS\Exception
     */
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->api = new MenuApi();
    }

    /**
     *  Возвращает массив меню для сайта
     *
     * @return \RS\Controller\Result\Standard
     * @throws \RS\Exception
     */
    function actionGetMenuList()
    {
        $root = $this->request('root', TYPE_INTEGER, 0);
        $showAll = $this->request('showAll', TYPE_INTEGER, 0);
        return $this->result->setSuccess(true)->addSection('list',  $this->api->getTreeForMenus($showAll, $root));
    }

    /**
     *  Возвращает массив категорий для сайта
     *
     * @return \RS\Controller\Result\Standard
     * @throws \RS\Exception
     */
    function actionGetCategoryList()
    {
        $root = $this->request('root', TYPE_INTEGER, 0);
        $showAll = $this->request('showAll', TYPE_INTEGER, 0);
        if ($showAll){
            $list = $this->api->getTreeForCategory($root);
        }else{
            $list = $this->api->getSimpleTreeForCategory($root);
        }
        return $this->result->setSuccess(true)->addSection('list',  $list);
    }
}