<?php
/**
* ReadyScript (http://readyscript.ru)
*
* @copyright Copyright (c) ReadyScript lab. (http://readyscript.ru)
* @license http://readyscript.ru/licenseAgreement/
*/
namespace Designer\Controller\Admin;

use Designer\Model\AtomApis\FormApi;
use RS\Controller\Admin\Front;

/**
 * Контроллер, позволяющий работать с компонентом формы
 */
class AtomFormCtrl extends Front
{
    /**
     * @var FormApi $api
     */
    protected $api;
    /**
     * Инициализация контроллера
     *
     * @throws \RS\Exception
     */
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!\RS\Module\Manager::staticModuleExists('feedback') || !\RS\Module\Manager::staticModuleEnabled('feedback')){
            $this->result->addEMessage(t('Для работы с формами необходимо иметь или включить модуль "Формы обратной связи" (feedback)'));
        }
        $this->api = new FormApi();
    }

    /**
     * Создает картинку по умолчанию для атома картинки и возвращает массив сведений по картинкам
     *
     * @return \RS\Controller\Result\Standard
     * @throws \RS\Orm\Exception
     */
    function actionGetFormById()
    {
        $form_id = $this->request('form_id', TYPE_INTEGER, 0);
        $form = $this->api->getFormData($form_id);

        return $this->result->setSuccess(true)->addSection('form', $form);
    }
}